export {default as Product} from './product'
export {default as MainTitle} from './mainTitle'
export {default as BreadCrumbs} from './breadcrumps'
export {default as SortSection} from './sort'
export {default as RelatedProduct} from './related product'
export {default as ShoppingCartProduct} from './cart product'
export {default as ProductSummarySection} from './product summary'
export {default as NotFound} from './404 Not Found'
export {default as NotItemShopping} from './not Item Shopping'
export {default as PaypalPaymentMethod} from './Paypal Payment'