export {default as Header} from './header'
export {default as Footer} from './footer'
export {default as SearchResultContent} from './search result'
export {default as UserRegister} from './auth/Register'
export {default as UserLogin} from './auth/Login'
export {default as UserSuccessOrErrorReg} from './auth/success register'
export {default as UserUpdateAvatar} from './header/components/user popUp/components/update Avatar'